# Gremlins mutation testing configuration

# Quality thresholds
# Set realistic thresholds accounting for system-level mutations that are impractical to test
threshold-efficacy: 90.0  # High efficacy - when we test, we should catch bugs
threshold-mcover: 25.0    # Lower coverage threshold - many mutations are system-level failures

# Performance settings
workers: 4
timeout-coefficient: 2

# Note: Some mutations represent system-level failures that are impractical to test:
# - os.Getwd() failures
# - File permission errors  
# - Viper configuration parsing edge cases
# These are acceptable to leave uncovered as they represent infrastructure failures
# rather than business logic bugs.