name: Mutation Testing

on:
  # Run on manual trigger
  workflow_dispatch:
  # Run weekly on Sundays at 2 AM UTC  
  schedule:
    - cron: '0 2 * * 0'
  # Run on pushes to main that change Go code (but not on every push)
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod' 
      - 'go.sum'
      - '.gremlins.yml'
      - '.github/workflows/mutation-test.yml'

jobs:
  mutation-test:
    name: Comprehensive Mutation Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.24-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.24-

    - name: Download dependencies
      run: go mod download

    - name: Install Gremlins
      run: go install github.com/go-gremlins/gremlins/cmd/gremlins@latest

    - name: Run comprehensive mutation tests
      run: |
        echo "🧪 Running comprehensive mutation testing..."
        echo "This may take a few minutes as it tests multiple mutations."
        echo ""
        echo "📋 Current thresholds:"
        echo "  - Test Efficacy: 90% (when we test, we catch bugs)"  
        echo "  - Mutator Coverage: 25% (realistic for system-level code)"
        echo ""
        
        # Run with detailed output
        gremlins unleash . --workers 2
        
        echo ""
        echo "✅ Mutation testing analysis complete!"
        echo ""
        echo "📊 Results Summary:"
        echo "- KILLED mutations: Tests successfully caught these bugs"
        echo "- NOT COVERED mutations: Code paths not exercised by tests"
        echo "- LIVED mutations: Tests ran but didn't catch these bugs (concerning!)"
        echo ""
        echo "💡 Focus on achieving high efficacy rather than high coverage."
        echo "   It's better to test fewer things well than many things poorly."

    - name: Upload mutation test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mutation-test-results
        path: |
          gremlins.log
        retention-days: 30
