name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Create dist directory
      run: mkdir -p dist

    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/jitt-linux-amd64 ./cmd/jitt
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o dist/jitt-linux-arm64 ./cmd/jitt
        
        # macOS  
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o dist/jitt-darwin-amd64 ./cmd/jitt
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o dist/jitt-darwin-arm64 ./cmd/jitt
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o dist/jitt-windows-amd64.exe ./cmd/jitt

    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/jitt-linux-amd64
          dist/jitt-linux-arm64
          dist/jitt-darwin-amd64
          dist/jitt-darwin-arm64
          dist/jitt-windows-amd64.exe
          dist/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
